// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace maringuizarapp.iOS{
	public partial class CartCellController : UITableViewCell{

		public string NombreProducto { 
			get { return nombreProducto.Text;}
			set { nombreProducto.Text = value;}
		}
		public CartCellController (IntPtr handle) : base (handle){
		}
	}
}
