// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace maringuizarapp.iOS{
	public partial class CartCellController : UITableViewCell{

		public string NombreProducto { 
			get { return nombreProducto.Text;}
			set { nombreProducto.Text = value;}
		}

		public string IDProduct { 
			get { return idProducto.Text;}
			set { idProducto.Text = value;}
		}

		public string PrecioVenta { 
			get { return precioVentaProducto.Text;}
			set { precioVentaProducto.Text = value;}
		}
		public CartCellController (IntPtr handle) : base (handle){
		}
	}
}
