// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace maringuizarapp.iOS
{
	public partial class ItemsCellController : UITableViewCell{

		public string NombreCorto {
			get { return labelCellNombreCorto.Text; }
			set { labelCellNombreCorto.Text = value;}

		}

		public string Existencia {
			get { return labelCellExistencia.Text;}
			set { labelCellExistencia.Text = value;}
		}

		public string PrecioVenta { 
			get { return labelCellPrecioVenta.Text;}
			set { labelCellPrecioVenta.Text = value;}
		}

		public string IDCodigo { 
			get { return labelCellIDCodigo.Text;}
			set { labelCellIDCodigo.Text = value;}
		}

		public string Grupo { 
			get { return labelCellGrupo.Text; }
			set { labelCellGrupo.Text = value;}
		}

		public ItemsCellController (IntPtr handle) : base (handle){
		}
	}
}
