// This file has been autogenerated from a class added in the UI designer.

using System;


using Foundation;
using UIKit;
using maringuizarapp.Service;
using maringuizarapp.Model;
using System.Collections.Generic;
using System.IO;

namespace maringuizarapp.iOS{
	public partial class LoginTestViewController : UIViewController{


		//string uuid = "F0:27:65:E8:19:69";
		//string url_API = "http://maringuizar.highbits.com/";

		public override void ViewDidLoad() {
			base.ViewDidLoad();

			Console.WriteLine("Iniciando LoginTestViewController...");

			//buttonIniciarSesion.TouchUpInside += ButtonIniciarSesion_TouchUpInside;
			buttonGJson.TouchUpInside += ButtonGJson_TouchUpInside;
		}

		void ButtonGJson_TouchUpInside(object sender, EventArgs e) {

			SaveFile();
		}

		async void SaveFile() {
			try {

				Service.Service servicio = new Service.Service();
				var jsonStr = await servicio.saveJsonFile();
				var documents = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);



				var filename = Path.Combine(documents, "allItems.json");
				File.WriteAllText(filename, jsonStr);

				//Console.WriteLine(jsonStr);

				myTextViewJ.Text = jsonStr;

				var sessioErrorAlert = UIAlertController.Create("Json Guardado", "OK", UIAlertControllerStyle.Alert);
				sessioErrorAlert.AddAction(UIAlertAction.Create("Ok", UIAlertActionStyle.Default, null));

				//myTextViewC.Text = jsonStr;
				PresentViewController(sessioErrorAlert, true, null);

			}
			catch (Exception e) {
				Console.WriteLine("El archivo json no se ha podido guardar!");
				var sessioErrorAlert = UIAlertController.Create("Json No Guardado", "OK", UIAlertControllerStyle.Alert);

				sessioErrorAlert.AddAction(UIAlertAction.Create("Ok", UIAlertActionStyle.Default, null));
				PresentViewController(sessioErrorAlert, true, null);

				Console.WriteLine(e);

			}	}
	

		//async void ButtonIniciarSesion_TouchUpInside(object sender, EventArgs e) {


		//	Console.WriteLine("touched buttonIniciarSesion"+CurrentSession.id_mac);

		//	string url = url_API + string.Format("serviceLogin?id={0}", uuid);

		//	Console.WriteLine(url);
		//	if (CurrentSession.admin_dispositivo == 44) {
		//			Console.WriteLine("Sesion Iniciada");
		//		}

		//	try {
		//		Console.WriteLine("Holaa!");
		//		Service.Service servicio = new Service.Service();
		//		var sesion = await servicio.LoginAsync("F02765E81969");
		//						Console.WriteLine(CurrentSession.admin_dispositivo+"sesion");

		//		Console.WriteLine("admin_dispositivo: "+CurrentSession.admin_dispositivo);
		//		if (CurrentSession.admin_dispositivo == 44) {
		//			Console.WriteLine("Sesion Iniciada");
		//		}

		//		Console.WriteLine(CurrentSession.admin_dispositivo+"sesion");
		//		Console.WriteLine();
		//		Console.WriteLine();


		//	//	if (sesion.id_mac == "920312") {
		//	//		Console.WriteLine("Logueo Exitoso");
		//	//}
		//	}
		//	catch {
		//		Console.WriteLine("Error de logueo!");
		//	}





		//}

		public LoginTestViewController (IntPtr handle) : base (handle){
		}
	}
}
