// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

using maringuizarapp.Service;
using maringuizarapp.Model;
using System.Collections.Generic;

namespace maringuizarapp.iOS{
	public partial class LoginViewController : UIViewController{




		public LoginViewController (IntPtr handle) : base (handle){
		}

		public override void ViewDidLoad() {
			base.ViewDidLoad();

			var uniqueID = UIKit.UIDevice.CurrentDevice.IdentifierForVendor.AsString();

			Console.WriteLine("UniqueID " + uniqueID);
			Console.WriteLine(uniqueID.Substring(0,8));

			buttonLogin.TouchUpInside += ButtonLogin_TouchUpInside;

		}

		//void saveFile(List<Producto> jsonObject) {
		//	//Serializando Objeto
		//	//var toJson = JsonConv

		//	var fileSaving = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);

		//}


		//METODO PARA RECIBIR JSON FILE Y GUARDARLO EN MyDocuments iOS
		//public void seveJsonFile() {
			//Obteniendo Desde Service JSONFILE
			
			//Guardando JsonDile en folder iOS
			
		//}

		async void ButtonLogin_TouchUpInside(object sender, EventArgs e) {
			Console.WriteLine("Iniciando sesion...");
			Service.Service servicio = new Service.Service();
			string uuid = labelUIDevice.Text;

			Console.WriteLine("Unique ID "+ uuid);



			try {
				var sesion = await servicio.LoginAsync(uuid);

				if (CurrentSession.id_mac == uuid) {
					Console.WriteLine("Session Iniciada Exitosamente!");
					statusLogin.Text = "Sesión Iniciada Correctamente!";

					//var productosViewController = (ProductosViewController)Storyboard.InstantiateViewController("ProductosViewController");
					//this.NavigationController.PushViewController(productosViewController, true);
					//var TabBar = (TabBarViewController)Storyboard.InstantiateViewController("TabBarViewController");
					//this.NavigationController.PushViewController(TabBar, true);


					var appDelegate =  UIApplication.SharedApplication.Delegate as AppDelegate;
					var rootViewController = new RootViewController();
					var productsView = (TabBarViewController)Storyboard.InstantiateViewController("TabBarViewController");
					appDelegate.SetRootViewController(productsView, true);

				} else {
					
					if (CurrentSession.id_mac != uuid || CurrentSession.id_mac == null || CurrentSession.id_mac == "") {


						var sessioErrorAlert = UIAlertController.Create("Error de Sesión", "Verifique ID de dispositivo con Admnistrador", UIAlertControllerStyle.Alert);


						sessioErrorAlert.AddAction (UIAlertAction.Create ("Ok", UIAlertActionStyle.Default, null));
						// Present Alert
						PresentViewController(sessioErrorAlert, true, null);
						statusLogin.BackgroundColor = UIColor.Red;
						statusLogin.Text = "Problemas al iniciar sesión";



					}

				}


			}
			catch {
				
			}



		}
	}
}
