// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace maringuizarapp.iOS
{
	public partial class PrincipalNavViewController : UINavigationController
	{
		public PrincipalNavViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
