// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;

using Foundation;
using UIKit;

namespace maringuizarapp.iOS{
	public partial class ProductDetailsViewController : UIViewController{

		string precioCostoFijo;
		string descripcion;
		string idProducto; 
		List<DetailProductStock> lstDetailProductStock;


		public string CostoFijo {
			get { return precioCostoFijo; }
			set { precioCostoFijo = value;}
		}

		public string idProduct { 
			get { return idProducto;}
			set { idProducto = value;}
		}
		public string Descripcion { 
			get { return descripcion;}
			set { descripcion = value;}
		}

		public override void ViewDidLoad() {
			base.ViewDidLoad();
			this.Title = "Detalles";

			labelPrecioCostoFijo.Text = precioCostoFijo;
			textViewDescripción.Text = descripcion;
		}

		public async  override void ViewWillAppear(bool animated) {
			base.ViewWillAppear(animated);

			try {
				Service.Service servicio = new Service.Service();
				Console.WriteLine("IdProducto"+idProduct +"  adasd" +idProducto);
				lstDetailProductStock = await servicio.DetailStock(idProducto);
				Console.WriteLine("Stock detalle " + lstDetailProductStock.Count);


			}
			catch {
				Console.WriteLine("Fallo solicitar stockDetail");
			}

		}

		public ProductDetailsViewController (IntPtr handle) : base (handle){
		}
	}
}
