// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace maringuizarapp.iOS{
	public partial class StockCellController : UITableViewCell{


		public string IdAlmacen { 
			get { return idAlmacenLabel.Text;}
			set { idAlmacenLabel.Text = value;}
		}

		public string IdMaterial { 
			get { return idMaterialLabel.Text;}
			set { idMaterialLabel.Text = value;}
		}

		public object NoAlmacen { 
			get { return noAlmacenLabel.Text;}
			set { noAlmacenLabel.Text = value.ToString();}
		}

		public string NombreAlmacen { 
			get { return nombreAlmacenLabel.Text;}
			set { nombreAlmacenLabel.Text = value;}

		}

		public object CantidadAlmacen { 
			get { return cantidadAlmacenLabel.Text;}
			set { cantidadAlmacenLabel.Text = value.ToString();}
		}

		public StockCellController (IntPtr handle) : base (handle){
		}
	}
}
